### ISSUE TITLE
Incorrect return error for send_command

### ISSUE THREAD

**Issue by v1tal3** [lykinsbd/naas#16]
If I run POST `send_command` with an incorrectly spelled "commands" variable in the payload, or if it's missing, I get a proper 400 error with a proper response.

If I run the same command, but instead incorrectly spell or omit the "ip" variable in the payload, I get a 500 error returned, with only the following:

```
{
    "message": "Internal Server Error"
}
```

**Comment by lykinsbd** [comment]
Problem is here: https://github.com/lykinsbd/naas/blob/master/naas/library/decorators.py#L21

Attempting to access `request.json["ip"]` instead of doing `request.json.get("ip", None)`

I'll fix this in some of the re-work I'm doing of the validation/decorators for API resources.

**Comment by lykinsbd** [comment]
Fixed in a1c05ae
